### ISSUE TITLE
Not working on iOS

### ISSUE THREAD

**Issue by svzi** [EinfachHans/capacitor-email-composer#10]
Hi @EinfachHans !

First of all thank you very much for the plugin! Sadly it doesn't work on iOS for me. When I try to call `EmailComposer.open(...)` I get this error message:
```
Error: "EmailComposer" plugin is not implemented on ios
```

I'm for sure using the latest version (1.1.3). From my understanding this plugin should be implemented on iOS as well, at least I can see some iOS source files. Any idea what's causing this issue for me?

Best,
Sven

**Comment by svzi** [comment]
Removing the plugin and adding it again solved my issue!

**Comment by marco24690** [comment]
Hi @svzi can I ask you to provide your usage example?I don't kwow how to import it, the class name to interact with and if it needs to be injected like a service

**Comment by svzi** [comment]
@marco24690 Import it like this 
```ts
import { EmailComposer, OpenOptions } from 'capacitor-email-composer';
```

And no need to inject any Capacitor 3 Plugins. Just use it like provided in the `README.md` in this repo.
