### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by muuvmuuv** [EinfachHans/capacitor-email-composer#11]
How much work would it be to support attachments? We would like to migrate from cordova-email-composer but require attachments being sent.

**Comment by EinfachHans** [comment]
Please send a link to the cordova plugin you are currently using

**Comment by muuvmuuv** [comment]
https://ionicframework.com/docs/native/email-composer

**Comment by autodisk-kjelt** [comment]
Is adding an attachment in the mail something that wil be added ?

**Comment by EinfachHans** [comment]
Version [**1.2.0**](https://github.com/EinfachHans/capacitor-email-composer/releases/tag/V1.2.0) was just released with attachment support and updated to capacitor 4 😊 Sorry for the long waiting time
