### ISSUE TITLE
iOS Compiler Version issue in Capacitor 4.01 and Ionic 6.2.2

### ISSUE THREAD

**Issue by sreejith-mv** [EinfachHans/capacitor-email-composer#14]
On Capacitor 4.01 and Ionic 6.2.2, I am getting an error in iOS for Plugin Compiler version. Could you please able to update the compiler version to 13? 

  ❌  /Users/runner/work/-----/node_modules/capacitor-email-composer/ios/Plugin/EmailComposer.swift:2:8: compiling for iOS 12.0, but module 'Capacitor' has a minimum deployment target of iOS 13.0: /Users/runner/Library/Developer/Xcode/DerivedData/App-evsdlgyukodovrgtwbzbgondoaey/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/Capacitor/Capacitor.framework/Modules/Capacitor.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by EinfachHans** [comment]
what version of this plugin is installed?

**Comment by sreejith-mv** [comment]
Version 1.2.0

**Comment by sreejith-mv** [comment]
Any update on this issue?

**Comment by EinfachHans** [comment]
just tested and cant reproduce 🤔

**Comment by sreejith-mv** [comment]
Please see the s.ios.deployment_target  = '12.0' in  https://github.com/EinfachHans/capacitor-email-composer/blob/dev/CapacitorEmailComposer.podspec. 

Could you please update it to 13 ?

**Comment by EinfachHans** [comment]
@sreejith-mv please create a PR, i will merge and release it directly 😊 Also please test your changes by installing your fork into your app and see if the problems are fixed
