### ISSUE TITLE
Error when launching Android "package android.content does not exist"

### ISSUE THREAD

**Issue by jwburnside** [EinfachHans/capacitor-email-composer#17]
I seem to be running into an issue launching with the build error: 

**error: package android.content does not exist
import android.content.Context;**

This seems to be the only package causing an issue, if I remove it the app launches fine.

I have attempted on two Android devices:
- Pixel 5 API 31 (emulated)
- Pixel 5 API 32 (physical device)

Here's my Ionic info and some Android settings, let me know if you have a solution or need more info. Thanks!

Ionic:

   Ionic CLI                     : 6.19.1 
   Ionic Framework               : @ionic/angular 6.2.6
   @angular-devkit/build-angular : 13.3.9
   @angular-devkit/schematics    : 13.3.9
   @angular/cli                  : 13.3.9
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.7.0
   @capacitor/android : 3.7.0
   @capacitor/core    : 3.7.0
   @capacitor/ios     : 3.7.0

variables.gradle

    minSdkVersion = 22
    compileSdkVersion = 32
    targetSdkVersion = 33
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion =  '10.1.1'
    // capacitor-background-geolocation variables
    googlePlayServicesLocationVersion = '18.0.0'

**Comment by EinfachHans** [comment]
Can#t reproduce that 🤔

**Comment by jwburnside** [comment]
Looks like this was a Java version issue with the latest package, we bumped it back to 1.1.3 and it is launching now.
