### ISSUE TITLE
open() is not a function

### ISSUE THREAD

**Issue by mikkimichaelis** [EinfachHans/capacitor-email-composer#20]
Following the example from npm runkit [https://npm.runkit.com/capacitor-email-composer](https://npm.runkit.com/capacitor-email-composer) and modifying the code to be as such:

```node
require("@capacitor/core/package.json"); // @capacitor/core is a peer dependency. 
var capacitorEmailComposer = require("capacitor-email-composer")
capacitorEmailComposer.open({})
```

I receive the error 'TypeError: capacitorEmailComposer.open is not a function’

When importing and using like this:

```node
import { EmailComposerPlugin } from 'capacitor-email-composer';
EmailComposerPlugin.open({})
```

I receive the same error 'TypeError: capacitorEmailComposer.open is not a function’

Thank you for your help.

**Comment by EinfachHans** [comment]
This plugin has no web implementation. Please open a new issue if you have problems in an native environment.
