### ISSUE TITLE
Unable to inject Capacitor, Plugins won't work

### ISSUE THREAD

**Issue by joshua22s** [EinfachHans/capacitor-email-composer#21]
I have used this plugin for a while in a Capacitor/Angular app I have developed for Android. I am updating this app to Capacitor 4 now but I am experiencing issues with the email-composer plugin. 

I have updated the capacitor-email-composer to version 1.2.1, and building the app works fine. But when I am trying to call the EmailComposer.open() function I get in Logcat: Unable to inject Capacitor, Plugins won't work.

This project also uses the capacitor-native-biometric plugin and that one seems to work fine.

I have tried rebuilding the Android project, reïnstalling the dependency but this doesn't seem to work.

Any clue on what the problem could be?

**Comment by EinfachHans** [comment]
Mhh, i use this plugin successfully in my v4 apps, can you please provide a small reproducable repo?

**Comment by EinfachHans** [comment]
Closed because no repo provided. If you still have problems please open a new issue
