### ISSUE TITLE
Capacitor 5 Support

### ISSUE THREAD

**Issue by muuvmuuv** [EinfachHans/capacitor-email-composer#22]
No hurry, just to track it. Cap 5 is out now. :)

**Comment by EinfachHans** [comment]
Thanks, released [V2.0.0](https://github.com/EinfachHans/capacitor-email-composer/releases/tag/V2.0.0) with Capacitor 5 Support 😊

**Comment by muuvmuuv** [comment]
EinfachSchnell! 😄👍🏻
