### ISSUE TITLE
JSON as attachment

### ISSUE THREAD

**Issue by wimZ** [EinfachHans/capacitor-email-composer#27]
Would it be possible to add the possibility to attach a large text i.e. a stringified JSON object,

I would like to avoid the cycle through the file system.

Kind regards
wim

**Comment by EinfachHans** [comment]
What would you expect exactly? 🤔 Passing a JSON string which should be added as a `.json` file?

**Comment by wimZ** [comment]
The simple answer is yes. 

I currently capture data in json format and need to store it first as file before attaching, and the removing the file again. 

ability to specify an attachment like: 
attachments: [{ filename: "xyz.json", content: "<content"} ]

**Comment by EinfachHans** [comment]
You could use base64, couldn't you? 🤔 This should work without need to really store the file on the device

**Comment by wimZ** [comment]
I overlooked this option completely. It works like a charm. 

Apologize for bothering.
