### ISSUE TITLE
EmailComposerPlugin.open gibes error, doesn't compile

### ISSUE THREAD

**Issue by swissfritz** [EinfachHans/capacitor-email-composer#29]
`import { Camera, CameraResultType, CameraSource } from '@capacitor/camera';
import { EmailComposerPlugin, OpenOptions } from 'capacitor-email-composer';
...
 async sendMail() {
    const options: OpenOptions = {
      to: ['fritzfrei45@gmail.com'],
      subject: 'Unfall',
      body: 'Meine Unfallfotos',
      attachments: [{
        type: "base64",
        path: 'data:image/jpeg;base64,${this.imageData}',
        name: 'Unfallfotos'
      }]
    };

    await EmailComposerPlugin.open(options?: OpenOptions);
  }

`gives a TS error (2693): 'EmailComposerPlugin' refers to an object but is being used as a value here.

When I initiate them in the  cinstructor ...

 constructor(public plug:EmailComposerPlugin, public opts: OpenOptions) 

and 

await this.plug.open(this.opts);

... npm run build gives the following error:

This type does not have a value, so it cannot be used as injection token.
  node_modules/capacitor-email-composer/dist/esm/definitions.d.ts:1:1
      1 export interface EmailComposerPlugin {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      2     /**
        ~~~~~~~``

**Comment by EinfachHans** [comment]
you don't have to inject capacitor plugins in the constructor. Remove it from there. Just import and use it directly

**Comment by swissfritz** [comment]
Danke Hans,
that's what I tried first and which gave me the TS-error "'EmailComposerPlugin' refers to an object but is being used as a value here." (see first part of my issue).
How can I get around that?

**Comment by EinfachHans** [comment]
please create a minimal reproducable repo

**Comment by swissfritz** [comment]
Gerne, https://github.com/swissfritz/einfach.git

Danke Hans!

Fritz

**Comment by swissfritz** [comment]
I wondered why OpenOptions didn't provoke a TS error, so I tried tinkering with the Plugins name and ... voilà: EmailComposer worked. So, if I import EmailComposer, OpenOptions from capacitor-email-composer and use them this way in the code, everything works fine. You may have a silent contributor who changed the plugins name to use?

**Comment by EinfachHans** [comment]
Thank you and sorry for the circumstances. Readme is adjusted 😊

**Comment by swissfritz** [comment]
Great! Thanks to you for this awesome plugin!
