### ISSUE TITLE
Feature Request - Callback on Email send/cancel

### ISSUE THREAD

**Issue by loneoakdev** [EinfachHans/capacitor-email-composer#31]
Love the plugin...much better than trying to use a Cordova plugin in an all Capacitor app.

I have a request if this is possible. I ran across this when testing an email send. After a user sends an email, I clear the form and display a success message. However, if the user cancels the action instead of clicking send, the form still clears and the success message displays because I don't know that they cancelled it...just that the email window has been closed.

Would it be possible to add a callback to the open() method to determine whether the email window was cancelled or if the email was actually sent?

Let me know what you think.
Thanks!

**Comment by EinfachHans** [comment]
Hey @loneoakdev,

thanks for your feature request and sorry for the delay 😊 

I just had a look into the native implementation. Seems like it is possible on iOS, but not on Android...
It sounds like a cool feature to me, but honestly i don't like the fact that we would can't be platform equal here. Developer then would still need to do things platform specific.

What are your thought on this?

**Comment by EinfachHans** [comment]
Closed die inactivity
