### ISSUE TITLE
[5.0.0] Send email with GMAIL html body no translate

### ISSUE THREAD

**Issue by YanouonaY** [EinfachHans/capacitor-email-composer#36]
Hello,

I use the library to send email. I send html body, it runs with outlook, but no with gmail, HTML tags and special characters no translate.

`open({to: 'toto', attachments: [], subject: 'toto', body: '<p></p><p>\r\n\t&gt;&gt; Toto &lt;&lt;<br />'})`

On iOS, it's ok !

Thanks

**Comment by EinfachHans** [comment]
Hey, please you please create a repository where i can reproduce this?

**Comment by YanouonaY** [comment]
I cannot share my project. But for you, on android phone, you can send mail with html body with GMAIL and OUTLOOK like this:

`open({to: 'toto', attachments: [], subject: 'toto', body: '<p>\r\n\t&gt;&gt; Toto &lt;&lt;<br /></p>'})` with isHtml false / true?

**Comment by EinfachHans** [comment]
You don't have to share your project. You have to create a new public repository with the minimum required code to reproduce the issue.
