### ISSUE TITLE
Send attachments from device storage

### ISSUE THREAD

**Issue by sam-higgs** [EinfachHans/capacitor-email-composer#38]
It would be nice to be able to send attachments that are stored on device storage using https://capacitorjs.com/docs/apis/filesystem, this was previously possible with https://www.npmjs.com/package/cordova-plugin-email-composer?activeTab=readme

**Comment by EinfachHans** [comment]
You can send attachments that are stored on the device: https://github.com/EinfachHans/capacitor-email-composer?tab=readme-ov-file#device-storage

**Comment by sam-higgs** [comment]
This doesn't appear to work for me, at least on iOS with:

const { uri } = Filesystem.writeFile({
    path,
    directory: Directory.Cache,
    data,
    encoding: Encoding.UTF8,
  });

{ path: uri, type: "absolute", name: "foo.txt" }

uri being something like "file:///var..." and the error is "File does not exist at absolute path"

**Comment by sam-higgs** [comment]
@EinfachHans Thanks, that seems to work!

**Comment by joseitor** [comment]
> This doesn't appear to work for me, at least on iOS with something like:
> 
> ```
> const { uri } = Filesystem.writeFile({
>     path, // name of file
>     directory: Directory.Cache, 
>     data, // JSON string 
>     encoding: Encoding.UTF8,
>   });
> ...
> await EmailComposer.open({ subject, attachments: [{ path: uri, type: "absolute", name: "foo.json" }] })
> ```
> 
> uri being something like **"file:///var..."** and the error is **"File does not exist at absolute path"**

I have the same problem, and if remove `file://` get the "Failed to get uri for file" error

this is my code:
```
const fileStats = await Filesystem.stat({
        path: fileName,
        directory: directory,
      });
if (fileStats.type === 'file' && fileStats.size > 100) {
        const uri = fileStats.uri.replace('file://', '');
        attachments.push({
          type: 'absolute',
          path: uri,
          name: REPORT_ERROR_FILE_NAME
        });
      }
    } catch (error) {
      this.logger.log('Error checking if file exists: ' + error);
    }
const email = {
      to: ['aaa@mail.com'],
      attachments: attachments.length > 0 ? attachments : undefined,
    };
    await EmailComposer.open(email);
```

**Comment by sam-higgs** [comment]
> > This doesn't appear to work for me, at least on iOS with something like:
> > ```
> > const { uri } = Filesystem.writeFile({
> >     path, // name of file
> >     directory: Directory.Cache, 
> >     data, // JSON string 
> >     encoding: Encoding.UTF8,
> >   });
> > ...
> > await EmailComposer.open({ subject, attachments: [{ path: uri, type: "absolute", name: "foo.json" }] })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > uri being something like **"file:///var..."** and the error is **"File does not exist at absolute path"**
> 
> I have the same problem, and if remove `file://` get the "Failed to get uri for file" error
> 
> this is my code:
> 
> ```
> const fileStats = await Filesystem.stat({
>         path: fileName,
>         directory: directory,
>       });
> if (fileStats.type === 'file' && fileStats.size > 100) {
>         const uri = fileStats.uri.replace('file://', '');
>         attachments.push({
>           type: 'absolute',
>           path: uri,
>           name: REPORT_ERROR_FILE_NAME
>         });
>       }
>     } catch (error) {
>       this.logger.log('Error checking if file exists: ' + error);
>     }
> const email = {
>       to: ['aaa@mail.com'],
>       attachments: attachments.length > 0 ? attachments : undefined,
>     };
>     await EmailComposer.open(email);
> ```

You need to remove an extra forward slash so `const uri = fileStats.uri.replace('file:///', '');`

**Comment by joseitor** [comment]
Can you re-open this issue? The problem keeps going

**Comment by sam-higgs** [comment]
This issue has reappeared for me with version 7.x
