### ISSUE TITLE
Usage Example Needed

### ISSUE THREAD

**Issue by johnson512n28** [EinfachHans/capacitor-email-composer#9]
Hi, thanks for making this plugin and supporting it!

Could you provide an example of how to use this plugin, or describe the steps of importing/injecting it into an Ionic project?

**Comment by EinfachHans** [comment]
did you read the readme? It should solve all questions

**Comment by johnson512n28** [comment]
Hans,

Thanks for the response.

Your read me should include a complete example of the plugin’s usage, such as the following.

As it is now, we don’t know what classes to use to interact with the plugin, or if they need to be injected as services or not.

import { Injectable } from ***@***.***/core';
import { EmailComposer, OpenOptions } from 'capacitor-email-composer';

@Injectable({
  providedIn: 'root'
})
export class EmailService {

  constructor() { }

  async openEmail(toEmail: string) {
    const email: OpenOptions = {
      to: [toEmail],
      subject: 'Support Question',
    };

    if (await EmailComposer.hasAccount()) {
      EmailComposer.open(email);
    } else {
      console.log(‘No email account.’);
    }
  }
}




Daniel Johnson

**Comment by marco24690** [comment]
hi @johnson512n28 same problem here, do you have some updates?
